// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PushFinal.Context;

#nullable disable

namespace PushFinal.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230720130841_add subscriptions")]
    partial class addsubscriptions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebPush.PushSubscription", b =>
                {
                    b.Property<string>("Endpoint")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Auth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("P256DH")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Endpoint");

                    b.ToTable("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
